#!/usr/bin/env python3
"""Generate src/ko_overrides.c from tools/i18n/strings_ko.csv.

Builds a flat, sorted (english -> korean) lookup table used at runtime by
ko_tr() in menu.c to translate entry->name / entry->help / entry->help2 /
entry->choices[i] AT DISPLAY TIME ONLY. entry->name itself is never touched,
so internal logic that compares against entry->name (menu_find_by_name,
config save/load, submenu matching, etc.) keeps working against the
original English strings.
"""
import csv
import sys

SRC_CSV = "strings_ko.csv"
OUT_C = "ko_overrides.c"

def c_escape(s):
    # Preserve intentional two-char "\n" sequences (already fixed up in the
    # CSV to be literal backslash+n, not real newlines) while escaping any
    # other backslash, and escape double quotes. Also defensively flatten
    # any real newline/carriage return that might have slipped through.
    s = s.replace("\r\n", "\\n").replace("\n", "\\n").replace("\r", "\\n")
    s = s.replace("\\", "\x00ESC\x00")          # stash all backslashes
    s = s.replace("\x00ESC\x00n", "\\n")         # restore intended \n
    s = s.replace("\x00ESC\x00", "\\\\")         # double any other backslash
    s = s.replace('"', '\\"')
    return s

def main():
    pairs = {}
    conflicts = []
    with open(SRC_CSV, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            en = row.get("english", "")
            ko = row.get("korean", "")
            if not en or not ko or en == ko:
                continue
            if en in pairs and pairs[en] != ko:
                conflicts.append((en, pairs[en], ko))
                continue
            pairs[en] = ko

    items = sorted(pairs.items(), key=lambda kv: kv[0])

    with open(OUT_C, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by tools/i18n/gen_ko_overrides.py from tools/i18n/strings_ko.csv\n")
        f.write("// Do not hand-edit - fix the CSV and re-run the generator instead.\n")
        f.write('#include "dryos.h"\n\n')
        f.write("extern int rbf_font_has_ext_glyphs(void);  /* rbf_font.c */\n\n")
        f.write("struct ko_pair { const char* en; const char* ko; };\n\n")
        f.write("static const struct ko_pair ko_overrides[] = {\n")
        for en, ko in items:
            f.write('    {"%s", "%s"},\n' % (c_escape(en), c_escape(ko)))
        f.write("};\n\n")
        f.write("#define KO_OVERRIDES_COUNT ((int)(sizeof(ko_overrides)/sizeof(ko_overrides[0])))\n\n")
        f.write("const char* ko_tr(const char* en)\n{\n")
        f.write("    if (!en) return en;\n")
        f.write("    /* Hangul glyphs (ML/FONTS/<name>.KOX) missing from the card: keep English\n")
        f.write("     * instead of drawing blank menu text */\n")
        f.write("    if (!rbf_font_has_ext_glyphs()) return en;\n")
        f.write("    int lo = 0, hi = KO_OVERRIDES_COUNT - 1;\n")
        f.write("    while (lo <= hi)\n    {\n")
        f.write("        int mid = (lo + hi) / 2;\n")
        f.write("        int c = strcmp(en, ko_overrides[mid].en);\n")
        f.write("        if (c == 0) return ko_overrides[mid].ko;\n")
        f.write("        else if (c < 0) hi = mid - 1;\n")
        f.write("        else lo = mid + 1;\n")
        f.write("    }\n")
        f.write("    return en;\n")
        f.write("}\n")

    print(f"Wrote {OUT_C}: {len(items)} entries, {len(conflicts)} conflicts skipped")
    for en, ko1, ko2 in conflicts[:20]:
        print(f"  CONFLICT: {en!r} -> {ko1!r} vs {ko2!r} (kept first)")

if __name__ == "__main__":
    main()

