#!/usr/bin/env python3
"""Generate the i18n string table (C) for one UI language.

Reads tools/i18n/lang/<lang>.csv and writes a sorted (english -> translation)
table plus i18n_tr(), used by menu.c AT DISPLAY TIME ONLY. entry->name itself
is never touched, so menu_find_by_name, config save/load and submenu matching
keep working against the original English strings.

--lang en (the default build) emits a pass-through i18n_tr() and needs no CSV.
The output is rewritten only when its content changes, so make doesn't
recompile it on every build.
"""
import argparse, csv, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))


def c_escape(s):
    # Keep intentional two-char "\n" sequences, escape every other backslash
    # and double quotes, and flatten any real newline that slipped through.
    s = s.replace("\r\n", "\\n").replace("\n", "\\n").replace("\r", "\\n")
    s = s.replace("\\", "\x00ESC\x00")
    s = s.replace("\x00ESC\x00n", "\\n")
    s = s.replace("\x00ESC\x00", "\\\\")
    return s.replace('"', '\\"')


def load_pairs(csv_path):
    pairs, conflicts = {}, []
    with open(csv_path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            en, tr = row.get("english", ""), row.get("translation", "")
            if not en or not tr or en == tr:
                continue
            if en in pairs:
                if pairs[en] != tr:
                    conflicts.append((en, pairs[en], tr))
                continue
            pairs[en] = tr
    return pairs, conflicts


def render_c(lang, items):
    out = ["// AUTO-GENERATED by tools/i18n/gen_strings.py (lang=%s)" % lang,
           "// Do not hand-edit - fix tools/i18n/lang/%s.csv instead." % lang,
           '#include "dryos.h"', ""]
    if not items:
        out += ["const char* i18n_tr(const char* en)", "{", "    return en;", "}", ""]
        return "\n".join(out)
    out += ["extern int rbf_font_has_ext_glyphs(void);  /* rbf_font.c */", "",
            "struct i18n_pair { const char* en; const char* tr; };", "",
            "static const struct i18n_pair i18n_table[] = {"]
    out += ['    {"%s", "%s"},' % (c_escape(en), c_escape(tr)) for en, tr in items]
    out += ["};", "",
            "#define I18N_COUNT ((int)(sizeof(i18n_table)/sizeof(i18n_table[0])))", "",
            "const char* i18n_tr(const char* en)", "{",
            "    if (!en) return en;",
            "    /* extension glyphs (ML/FONTS/<name>.RBX) missing from the card: keep English",
            "     * instead of drawing blank menu text */",
            "    if (!rbf_font_has_ext_glyphs()) return en;",
            "    int lo = 0, hi = I18N_COUNT - 1;",
            "    while (lo <= hi)", "    {",
            "        int mid = (lo + hi) / 2;",
            "        int c = strcmp(en, i18n_table[mid].en);",
            "        if (c == 0) return i18n_table[mid].tr;",
            "        else if (c < 0) hi = mid - 1;",
            "        else lo = mid + 1;",
            "    }",
            "    return en;", "}", ""]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--lang", default="en")
    ap.add_argument("--out", required=True)
    ap.add_argument("--csv-dir", default=os.path.join(HERE, "lang"))
    a = ap.parse_args()

    items, conflicts = [], []
    if a.lang != "en":
        path = os.path.join(a.csv_dir, a.lang + ".csv")
        if not os.path.exists(path):
            sys.exit("gen_strings: no translation file %s" % path)
        pairs, conflicts = load_pairs(path)
        # strcmp() compares bytes; UTF-8 byte order == codepoint order
        items = sorted(pairs.items(), key=lambda kv: kv[0].encode("utf-8"))

    src = render_c(a.lang, items)
    old = open(a.out, encoding="utf-8").read() if os.path.exists(a.out) else None
    if src != old:
        with open(a.out, "w", encoding="utf-8") as f:
            f.write(src)
    print("gen_strings: lang=%s %d entries, %d conflicts (kept first)%s"
          % (a.lang, len(items), len(conflicts), "" if src != old else ", unchanged"))
    for en, t1, t2 in conflicts[:20]:
        print("  CONFLICT: %r -> %r vs %r" % (en, t1, t2))


if __name__ == "__main__":
    main()
